language: php
php:
- '5.3'
- '5.4'
- '5.5'
- '5.6'
- '7.0'
- nightly
env:
  global:
    secure: BoT3I123WhF1aUDvoOfZ9XKUeXEkx/fK7/o2Ad7G4+Eq7Xc9b9/s2D2vQA7fuQIbjTF8tkriaP+rOYaEsAP/dKg0ZQ7DgdrIoNFgPolsAQkWthqLtXuTvsQ49BPy0E+XrVKTOQO7desHr3ekKJbeyDWbdE5fenmp8lZNEpE8z/k33bjzKzhFU2Y1QJEEPQLAts4Bg1M81kCmBRPPEeZCUlK4AQJOjsqE20PLFo5hXyJZvm3fQJipy1uB7mqZdl3jc8qxgffIzkkZufH0rDJ1cIBUNjO8m7MaNgTtC9uCz/xD6Akkz0joLWzqksnatV+cc89BowSzAmPoVJA55Ry8/FzA9Qc0Ew0kW6GA/rkKYdE4VgSTIQSp9aU5E86ZwzBsNpbbgB9NTCx8pEbZkNqv8Ytl6CKfNHwj+oBIC0RfAWH8ZiS+ywCya/qkLAfP0Sr/S+ZdF4awxCmNCWnqFOHg7PBJ28RRrjl/yHz59O1k9peOrm8qJE9q2ymSbkpDDq9rSV+sMiTFZok1A+fKrYsK4S48rtufXCUNmA4vTpx76dclWHMMDYyQam1xerGeyuaS4CXbYnCjJ1W4SePd4s6zrqL1lRKMfVO8YlW4aYb49Fz2nZ9uSgUjdvmQ2fR1ax/Yn5lxaVSagl2/IfHoNMw+0x2spthvUVLBNDNRAgxXRbA=
notifications:
  slack:
    secure: X5ejyz3yXvabXyVuhJ1T3P4Snv+URsW3llnzSuJRlfdB/X5yzs3yQsCyiIdyxR9xFIpSb5gJvSxCaxKrAsZKCeOPwGwyNY4H+RpO92Fq3LBDqEuaJdbv5LqfBSelRIdC9v//ViJd40Wh6vhVcW6jBtnQPhSCuGvDtTkCDmBHBV5x/ysqyc2LInbCc6QibPS6iygFYh9ez/TYWzx2QrGw5+lho1q/bZpbh9SEb1bQlqjGdRZ1pT6k4kIpXydWYrZYOfsVt5CoD9diJrGlRKRqBVFb1fbh/S3ZFpaX4CYeN9yXfIndwnTasnM4VHsmiZNRcUFkUtUU8C80QFMeNtWmaNHaiaKspBg8NaNyQiABpySJYgC5M4v1p9FsdaIuMZNxl0ZaklKYtV/wrERlKFYESpXo/csHV8lKJiG0ajMgHEFhoLtqzI/a22VGAmEoDGTaIOQETm6iWqmuwqBnVT7DFrUHE+KIy71/Ju01Jq9ue4mh4OnPDi1CyQ2JbGgiiD2qK5l588LkLgONYqokDPTf13zRa6WQQgC7jkRejJj8iVVuv6LAnxYXHdhdEgp+kb94oWIonvWbCA7Vs9rxVdFhxmqP/MnLif8Y65VeJJ/zUD50GpDwmKrIYYGjL3ZeIIP+J5w/5Rlj/303tOwBzwDwiIlDD/VC7amKKC3YOUO5ZHc=
before_install:
- sudo apt-get install -y graphviz
- phpenv config-add xsl.ini
install:
- composer install
before_script:
- mkdir -p docs
- mkdir -p coverage
after_success:
- "./vendor/bin/phpdoc"
- bash .travis_after_script.sh
